const GROUND_BLUE = '#478bff'

export const INITIAL_ROOM_LIGHT_SCALE = 0.035
export const DIM_ROOM_HOLD_SECONDS = 1

export const sceneSettings = {
  roomColor: GROUND_BLUE,
  floorColor: GROUND_BLUE,
  textColor: '#ffffff',
  floorOpacity: 1,
  textOpacity: 1,
  floorRoughness: 0.72,
  textRoughness: 1,
  floorMetalness: 0,
  textMetalness: 0,
  floorClearcoat: 0,
  textClearcoat: 0,
  floorClearcoatRoughness: 0.5,
  textClearcoatRoughness: 0,
  floorReflectivity: 0.5,
  textReflectivity: 0,
  floorIor: 1.5,
  textIor: 1.5,
  floorTransmission: 0,
  textTransmission: 0,
  floorThickness: 0,
  textThickness: 0,
  floorSheen: 0,
  textSheen: 0,
  floorSheenRoughness: 1,
  textSheenRoughness: 1,
  floorSheenColor: '#ffffff',
  textSheenColor: '#ffffff',
  floorSpecularIntensity: 1,
  textSpecularIntensity: 0.67,
  floorSpecularColor: '#ffffff',
  textSpecularColor: '#ffffff',
  floorIridescence: 0,
  textIridescence: 0,
  floorIridescenceIOR: 1.3,
  textIridescenceIOR: 1.3,
  floorWireframe: false,
  textWireframe: false,
  floorReceivesShadow: true,
  textCastsShadow: true,
  backgroundHighlightColor: '#9cc0ff',
  backgroundShadowColor: '#276ee8',
  backgroundAccentColor: '#185ce0',
  toneMappingExposure: 1,
  cameraViewSizeDesktop: 6.2,
  cameraViewSizeMobile: 15.6,
  hemisphereSkyColor: '#8ab9ff',
  hemisphereGroundColor: GROUND_BLUE,
  hemisphereIntensity: 0.79,
  keyColor: '#ccddff',
  keyIntensity: 1.3,
  fillColor: '#6190ff',
  fillIntensity: 0.44,
  accentColor: '#ffffff',
  accentIntensity: 1.7,
  accentDistance: 16,
  spotColor: '#ffffff',
  spotIntensity: 5.7,
  spotDistance: 50,
  spotAngle: 0.65,
  spotPenumbra: 0.61,
  spotDecay: 0.86,
  textPositionX: 0,
  textPositionY: 0,
  textPositionZ: -0.55,
  textRotationX: 0,
  textRotationY: 0,
  textRotationZ: 0,
  textScale: 1,
  transformControlsEnabled: true,
  transformControlsMode: 'translate' as const,
  transformControlsSize: 0.75,
  transformControlsSpace: 'world' as const,
  transformControlsShowX: true,
  transformControlsShowY: true,
  transformControlsShowZ: true,
  scrollForwardOffset: 0,
  scrollForwardMin: 0,
  scrollForwardMax: 35,
  clickImpulseStrength: 1.45,
  showColliderDebug: false,
}

export const initialSceneSettings = structuredClone(sceneSettings)
